@echo --- GROUP 1 --- time: %time%
@echo testcase: 1   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.01.in > ..\data\secret\g1\railway.01.ans
@echo testcase: 2   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.02.in > ..\data\secret\g1\railway.02.ans
@echo testcase: 3   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.03.in > ..\data\secret\g1\railway.03.ans
@echo testcase: 4   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.04.in > ..\data\secret\g1\railway.04.ans
@echo testcase: 5   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.05.in > ..\data\secret\g1\railway.05.ans
@echo testcase: 6   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.06.in > ..\data\secret\g1\railway.06.ans
@echo testcase: 7   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.07.in > ..\data\secret\g1\railway.07.ans
@echo testcase: 8   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.08.in > ..\data\secret\g1\railway.08.ans
@echo testcase: 9   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.09.in > ..\data\secret\g1\railway.09.ans
@echo testcase: 10   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.10.in > ..\data\secret\g1\railway.10.ans
@echo testcase: 11   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.11.in > ..\data\secret\g1\railway.11.ans
@echo testcase: 12   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.12.in > ..\data\secret\g1\railway.12.ans
@echo testcase: 13   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.13.in > ..\data\secret\g1\railway.13.ans
@echo testcase: 14   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g1\railway.14.in > ..\data\secret\g1\railway.14.ans
@echo --- END GROUP 1 --- time: %time%
@echo --- GROUP 2 --- time: %time%
@echo testcase: 1   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.01.in > ..\data\secret\g2\railway.01.ans
@echo testcase: 2   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.02.in > ..\data\secret\g2\railway.02.ans
@echo testcase: 3   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.03.in > ..\data\secret\g2\railway.03.ans
@echo testcase: 4   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.04.in > ..\data\secret\g2\railway.04.ans
@echo testcase: 5   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.05.in > ..\data\secret\g2\railway.05.ans
@echo testcase: 6   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.06.in > ..\data\secret\g2\railway.06.ans
@echo testcase: 7   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.07.in > ..\data\secret\g2\railway.07.ans
@echo testcase: 8   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.08.in > ..\data\secret\g2\railway.08.ans
@echo testcase: 9   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.09.in > ..\data\secret\g2\railway.09.ans
@echo testcase: 10   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.10.in > ..\data\secret\g2\railway.10.ans
@echo testcase: 11   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.11.in > ..\data\secret\g2\railway.11.ans
@echo testcase: 12   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.12.in > ..\data\secret\g2\railway.12.ans
@echo testcase: 13   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.13.in > ..\data\secret\g2\railway.13.ans
@echo testcase: 14   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.14.in > ..\data\secret\g2\railway.14.ans
@echo testcase: 15   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.15.in > ..\data\secret\g2\railway.15.ans
@echo testcase: 16   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.16.in > ..\data\secret\g2\railway.16.ans
@echo testcase: 17   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.17.in > ..\data\secret\g2\railway.17.ans
@echo testcase: 18   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.18.in > ..\data\secret\g2\railway.18.ans
@echo testcase: 19   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.19.in > ..\data\secret\g2\railway.19.ans
@echo testcase: 20   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.20.in > ..\data\secret\g2\railway.20.ans
@echo testcase: 21   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g2\railway.21.in > ..\data\secret\g2\railway.21.ans
@echo --- END GROUP 2 --- time: %time%
@echo --- GROUP 3 --- time: %time%
@echo testcase: 1   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g3\railway.01.in > ..\data\secret\g3\railway.01.ans
@echo testcase: 2   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g3\railway.02.in > ..\data\secret\g3\railway.02.ans
@echo testcase: 3   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g3\railway.03.in > ..\data\secret\g3\railway.03.ans
@echo testcase: 4   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g3\railway.04.in > ..\data\secret\g3\railway.04.ans
@echo testcase: 5   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g3\railway.05.in > ..\data\secret\g3\railway.05.ans
@echo testcase: 6   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g3\railway.06.in > ..\data\secret\g3\railway.06.ans
@echo --- END GROUP 3 --- time: %time%
@echo --- GROUP 4 --- time: %time%
@echo testcase: 1   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g4\railway.01.in > ..\data\secret\g4\railway.01.ans
@echo testcase: 2   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g4\railway.02.in > ..\data\secret\g4\railway.02.ans
@echo testcase: 3   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g4\railway.03.in > ..\data\secret\g4\railway.03.ans
@echo testcase: 4   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g4\railway.04.in > ..\data\secret\g4\railway.04.ans
@echo testcase: 5   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g4\railway.05.in > ..\data\secret\g4\railway.05.ans
@echo testcase: 6   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g4\railway.06.in > ..\data\secret\g4\railway.06.ans
@echo testcase: 7   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g4\railway.07.in > ..\data\secret\g4\railway.07.ans
@echo --- END GROUP 4 --- time: %time%
@echo --- GROUP 5 --- time: %time%
@echo testcase: 1   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.01.in > ..\data\secret\g5\railway.01.ans
@echo testcase: 2   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.02.in > ..\data\secret\g5\railway.02.ans
@echo testcase: 3   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.03.in > ..\data\secret\g5\railway.03.ans
@echo testcase: 4   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.04.in > ..\data\secret\g5\railway.04.ans
@echo testcase: 5   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.05.in > ..\data\secret\g5\railway.05.ans
@echo testcase: 6   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.06.in > ..\data\secret\g5\railway.06.ans
@echo testcase: 7   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.07.in > ..\data\secret\g5\railway.07.ans
@echo testcase: 8   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.08.in > ..\data\secret\g5\railway.08.ans
@echo testcase: 9   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.09.in > ..\data\secret\g5\railway.09.ans
@echo testcase: 10   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.10.in > ..\data\secret\g5\railway.10.ans
@echo testcase: 11   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.11.in > ..\data\secret\g5\railway.11.ans
@echo testcase: 12   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.12.in > ..\data\secret\g5\railway.12.ans
@echo testcase: 13   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.13.in > ..\data\secret\g5\railway.13.ans
@echo testcase: 14   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.14.in > ..\data\secret\g5\railway.14.ans
@echo testcase: 15   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g5\railway.15.in > ..\data\secret\g5\railway.15.ans
@echo --- END GROUP 5 --- time: %time%
@echo --- GROUP 6 --- time: %time%
@echo testcase: 1   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.01.in > ..\data\secret\g6\railway.01.ans
@echo testcase: 2   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.02.in > ..\data\secret\g6\railway.02.ans
@echo testcase: 3   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.03.in > ..\data\secret\g6\railway.03.ans
@echo testcase: 4   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.04.in > ..\data\secret\g6\railway.04.ans
@echo testcase: 5   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.05.in > ..\data\secret\g6\railway.05.ans
@echo testcase: 6   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.06.in > ..\data\secret\g6\railway.06.ans
@echo testcase: 7   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.07.in > ..\data\secret\g6\railway.07.ans
@echo testcase: 8   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.08.in > ..\data\secret\g6\railway.08.ans
@echo testcase: 9   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.09.in > ..\data\secret\g6\railway.09.ans
@echo testcase: 10   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.10.in > ..\data\secret\g6\railway.10.ans
@echo testcase: 11   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.11.in > ..\data\secret\g6\railway.11.ans
@echo testcase: 12   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.12.in > ..\data\secret\g6\railway.12.ans
@echo testcase: 13   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.13.in > ..\data\secret\g6\railway.13.ans
@echo testcase: 14   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.14.in > ..\data\secret\g6\railway.14.ans
@echo testcase: 15   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.15.in > ..\data\secret\g6\railway.15.ans
@echo testcase: 16   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.16.in > ..\data\secret\g6\railway.16.ans
@echo testcase: 17   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.17.in > ..\data\secret\g6\railway.17.ans
@echo testcase: 18   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.18.in > ..\data\secret\g6\railway.18.ans
@echo testcase: 19   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.19.in > ..\data\secret\g6\railway.19.ans
@echo testcase: 20   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.20.in > ..\data\secret\g6\railway.20.ans
@echo testcase: 21   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.21.in > ..\data\secret\g6\railway.21.ans
@echo testcase: 22   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.22.in > ..\data\secret\g6\railway.22.ans
@echo testcase: 23   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.23.in > ..\data\secret\g6\railway.23.ans
@echo testcase: 24   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.24.in > ..\data\secret\g6\railway.24.ans
@echo testcase: 25   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.25.in > ..\data\secret\g6\railway.25.ans
@echo testcase: 26   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.26.in > ..\data\secret\g6\railway.26.ans
@echo testcase: 27   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.27.in > ..\data\secret\g6\railway.27.ans
@echo testcase: 28   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.28.in > ..\data\secret\g6\railway.28.ans
@echo testcase: 29   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.29.in > ..\data\secret\g6\railway.29.ans
@echo testcase: 30   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.30.in > ..\data\secret\g6\railway.30.ans
@echo testcase: 31   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.31.in > ..\data\secret\g6\railway.31.ans
@echo testcase: 32   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.32.in > ..\data\secret\g6\railway.32.ans
@echo testcase: 33   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.33.in > ..\data\secret\g6\railway.33.ans
@echo testcase: 34   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.34.in > ..\data\secret\g6\railway.34.ans
@echo testcase: 35   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.35.in > ..\data\secret\g6\railway.35.ans
@echo testcase: 36   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.36.in > ..\data\secret\g6\railway.36.ans
@echo testcase: 37   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.37.in > ..\data\secret\g6\railway.37.ans
@echo testcase: 38   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.38.in > ..\data\secret\g6\railway.38.ans
@echo testcase: 39   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.39.in > ..\data\secret\g6\railway.39.ans
@echo testcase: 40   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.40.in > ..\data\secret\g6\railway.40.ans
@echo testcase: 41   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.41.in > ..\data\secret\g6\railway.41.ans
@echo testcase: 42   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.42.in > ..\data\secret\g6\railway.42.ans
@echo testcase: 43   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.43.in > ..\data\secret\g6\railway.43.ans
@echo testcase: 44   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.44.in > ..\data\secret\g6\railway.44.ans
@echo testcase: 45   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.45.in > ..\data\secret\g6\railway.45.ans
@echo testcase: 46   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.46.in > ..\data\secret\g6\railway.46.ans
@echo testcase: 47   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.47.in > ..\data\secret\g6\railway.47.ans
@echo testcase: 48   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.48.in > ..\data\secret\g6\railway.48.ans
@echo testcase: 49   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.49.in > ..\data\secret\g6\railway.49.ans
@echo testcase: 50   time: %time% 
@..\submissions\accepted\railway < ..\data\secret\g6\railway.50.in > ..\data\secret\g6\railway.50.ans
@echo --- END GROUP 6 --- time: %time%
