@echo --- GROUP 1 --- time: %time%
@echo testcase: 1
@pfi < ..\data\secret\g1\railway.01.ans
@echo testcase: 2
@pfi < ..\data\secret\g1\railway.02.ans
@echo testcase: 3
@pfi < ..\data\secret\g1\railway.03.ans
@echo testcase: 4
@pfi < ..\data\secret\g1\railway.04.ans
@echo testcase: 5
@pfi < ..\data\secret\g1\railway.05.ans
@echo testcase: 6
@pfi < ..\data\secret\g1\railway.06.ans
@echo testcase: 7
@pfi < ..\data\secret\g1\railway.07.ans
@echo testcase: 8
@pfi < ..\data\secret\g1\railway.08.ans
@echo testcase: 9
@pfi < ..\data\secret\g1\railway.09.ans
@echo testcase: 10
@pfi < ..\data\secret\g1\railway.10.ans
@echo testcase: 11
@pfi < ..\data\secret\g1\railway.11.ans
@echo testcase: 12
@pfi < ..\data\secret\g1\railway.12.ans
@echo testcase: 13
@pfi < ..\data\secret\g1\railway.13.ans
@echo testcase: 14
@pfi < ..\data\secret\g1\railway.14.ans
@echo --- END GROUP 1 --- time: %time%
@echo --- GROUP 2 --- time: %time%
@echo testcase: 1
@pfi < ..\data\secret\g2\railway.01.ans
@echo testcase: 2
@pfi < ..\data\secret\g2\railway.02.ans
@echo testcase: 3
@pfi < ..\data\secret\g2\railway.03.ans
@echo testcase: 4
@pfi < ..\data\secret\g2\railway.04.ans
@echo testcase: 5
@pfi < ..\data\secret\g2\railway.05.ans
@echo testcase: 6
@pfi < ..\data\secret\g2\railway.06.ans
@echo testcase: 7
@pfi < ..\data\secret\g2\railway.07.ans
@echo testcase: 8
@pfi < ..\data\secret\g2\railway.08.ans
@echo testcase: 9
@pfi < ..\data\secret\g2\railway.09.ans
@echo testcase: 10
@pfi < ..\data\secret\g2\railway.10.ans
@echo testcase: 11
@pfi < ..\data\secret\g2\railway.11.ans
@echo testcase: 12
@pfi < ..\data\secret\g2\railway.12.ans
@echo testcase: 13
@pfi < ..\data\secret\g2\railway.13.ans
@echo testcase: 14
@pfi < ..\data\secret\g2\railway.14.ans
@echo testcase: 15
@pfi < ..\data\secret\g2\railway.15.ans
@echo testcase: 16
@pfi < ..\data\secret\g2\railway.16.ans
@echo testcase: 17
@pfi < ..\data\secret\g2\railway.17.ans
@echo testcase: 18
@pfi < ..\data\secret\g2\railway.18.ans
@echo testcase: 19
@pfi < ..\data\secret\g2\railway.19.ans
@echo testcase: 20
@pfi < ..\data\secret\g2\railway.20.ans
@echo testcase: 21
@pfi < ..\data\secret\g2\railway.21.ans
@echo --- END GROUP 2 --- time: %time%
@echo --- GROUP 3 --- time: %time%
@echo testcase: 1
@pfi < ..\data\secret\g3\railway.01.ans
@echo testcase: 2
@pfi < ..\data\secret\g3\railway.02.ans
@echo testcase: 3
@pfi < ..\data\secret\g3\railway.03.ans
@echo testcase: 4
@pfi < ..\data\secret\g3\railway.04.ans
@echo testcase: 5
@pfi < ..\data\secret\g3\railway.05.ans
@echo testcase: 6
@pfi < ..\data\secret\g3\railway.06.ans
@echo --- END GROUP 3 --- time: %time%
@echo --- GROUP 4 --- time: %time%
@echo testcase: 1
@pfi < ..\data\secret\g4\railway.01.ans
@echo testcase: 2
@pfi < ..\data\secret\g4\railway.02.ans
@echo testcase: 3
@pfi < ..\data\secret\g4\railway.03.ans
@echo testcase: 4
@pfi < ..\data\secret\g4\railway.04.ans
@echo testcase: 5
@pfi < ..\data\secret\g4\railway.05.ans
@echo testcase: 6
@pfi < ..\data\secret\g4\railway.06.ans
@echo testcase: 7
@pfi < ..\data\secret\g4\railway.07.ans
@echo --- END GROUP 4 --- time: %time%
@echo --- GROUP 5 --- time: %time%
@echo testcase: 1
@pfi < ..\data\secret\g5\railway.01.ans
@echo testcase: 2
@pfi < ..\data\secret\g5\railway.02.ans
@echo testcase: 3
@pfi < ..\data\secret\g5\railway.03.ans
@echo testcase: 4
@pfi < ..\data\secret\g5\railway.04.ans
@echo testcase: 5
@pfi < ..\data\secret\g5\railway.05.ans
@echo testcase: 6
@pfi < ..\data\secret\g5\railway.06.ans
@echo testcase: 7
@pfi < ..\data\secret\g5\railway.07.ans
@echo testcase: 8
@pfi < ..\data\secret\g5\railway.08.ans
@echo testcase: 9
@pfi < ..\data\secret\g5\railway.09.ans
@echo testcase: 10
@pfi < ..\data\secret\g5\railway.10.ans
@echo testcase: 11
@pfi < ..\data\secret\g5\railway.11.ans
@echo testcase: 12
@pfi < ..\data\secret\g5\railway.12.ans
@echo testcase: 13
@pfi < ..\data\secret\g5\railway.13.ans
@echo testcase: 14
@pfi < ..\data\secret\g5\railway.14.ans
@echo testcase: 15
@pfi < ..\data\secret\g5\railway.15.ans
@echo --- END GROUP 5 --- time: %time%
@echo --- GROUP 6 --- time: %time%
@echo testcase: 1
@pfi < ..\data\secret\g6\railway.01.ans
@echo testcase: 2
@pfi < ..\data\secret\g6\railway.02.ans
@echo testcase: 3
@pfi < ..\data\secret\g6\railway.03.ans
@echo testcase: 4
@pfi < ..\data\secret\g6\railway.04.ans
@echo testcase: 5
@pfi < ..\data\secret\g6\railway.05.ans
@echo testcase: 6
@pfi < ..\data\secret\g6\railway.06.ans
@echo testcase: 7
@pfi < ..\data\secret\g6\railway.07.ans
@echo testcase: 8
@pfi < ..\data\secret\g6\railway.08.ans
@echo testcase: 9
@pfi < ..\data\secret\g6\railway.09.ans
@echo testcase: 10
@pfi < ..\data\secret\g6\railway.10.ans
@echo testcase: 11
@pfi < ..\data\secret\g6\railway.11.ans
@echo testcase: 12
@pfi < ..\data\secret\g6\railway.12.ans
@echo testcase: 13
@pfi < ..\data\secret\g6\railway.13.ans
@echo testcase: 14
@pfi < ..\data\secret\g6\railway.14.ans
@echo testcase: 15
@pfi < ..\data\secret\g6\railway.15.ans
@echo testcase: 16
@pfi < ..\data\secret\g6\railway.16.ans
@echo testcase: 17
@pfi < ..\data\secret\g6\railway.17.ans
@echo testcase: 18
@pfi < ..\data\secret\g6\railway.18.ans
@echo testcase: 19
@pfi < ..\data\secret\g6\railway.19.ans
@echo testcase: 20
@pfi < ..\data\secret\g6\railway.20.ans
@echo testcase: 21
@pfi < ..\data\secret\g6\railway.21.ans
@echo testcase: 22
@pfi < ..\data\secret\g6\railway.22.ans
@echo testcase: 23
@pfi < ..\data\secret\g6\railway.23.ans
@echo testcase: 24
@pfi < ..\data\secret\g6\railway.24.ans
@echo testcase: 25
@pfi < ..\data\secret\g6\railway.25.ans
@echo testcase: 26
@pfi < ..\data\secret\g6\railway.26.ans
@echo testcase: 27
@pfi < ..\data\secret\g6\railway.27.ans
@echo testcase: 28
@pfi < ..\data\secret\g6\railway.28.ans
@echo testcase: 29
@pfi < ..\data\secret\g6\railway.29.ans
@echo testcase: 30
@pfi < ..\data\secret\g6\railway.30.ans
@echo testcase: 31
@pfi < ..\data\secret\g6\railway.31.ans
@echo testcase: 32
@pfi < ..\data\secret\g6\railway.32.ans
@echo testcase: 33
@pfi < ..\data\secret\g6\railway.33.ans
@echo testcase: 34
@pfi < ..\data\secret\g6\railway.34.ans
@echo testcase: 35
@pfi < ..\data\secret\g6\railway.35.ans
@echo testcase: 36
@pfi < ..\data\secret\g6\railway.36.ans
@echo testcase: 37
@pfi < ..\data\secret\g6\railway.37.ans
@echo testcase: 38
@pfi < ..\data\secret\g6\railway.38.ans
@echo testcase: 39
@pfi < ..\data\secret\g6\railway.39.ans
@echo testcase: 40
@pfi < ..\data\secret\g6\railway.40.ans
@echo testcase: 41
@pfi < ..\data\secret\g6\railway.41.ans
@echo testcase: 42
@pfi < ..\data\secret\g6\railway.42.ans
@echo testcase: 43
@pfi < ..\data\secret\g6\railway.43.ans
@echo testcase: 44
@pfi < ..\data\secret\g6\railway.44.ans
@echo testcase: 45
@pfi < ..\data\secret\g6\railway.45.ans
@echo testcase: 46
@pfi < ..\data\secret\g6\railway.46.ans
@echo testcase: 47
@pfi < ..\data\secret\g6\railway.47.ans
@echo testcase: 48
@pfi < ..\data\secret\g6\railway.48.ans
@echo testcase: 49
@pfi < ..\data\secret\g6\railway.49.ans
@echo testcase: 50
@pfi < ..\data\secret\g6\railway.50.ans
@echo --- END GROUP 6 --- time: %time%
